name: lumen
volumes:
    postgres_data:

services:
    db:
        image: postgres:15.1-alpine
        container_name: lumina-postgres
        environment:
            POSTGRES_USER: lumina
            POSTGRES_DB: lumina
            POSTGRES_PASSWORD: 1
        expose:
            - "5432"
        volumes:
            - postgres_data:/var/lib/postgresql
        mem_swappiness: 0

    lumina:
        build: .
        depends_on:
            - db
        ports:
            - 1234:1234
            - 8082:8082
        environment:
            PKCSPASSWD: $PKCSPASSWD
        volumes:
            - ./dockershare:/dockershare
        links:
            - db
